/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_questdb_std_Files */

#ifndef _Included_com_questdb_std_Files
#define _Included_com_questdb_std_Files
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_questdb_std_Files
 * Method:    close0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_std_Files_close0
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
