/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_questdb_network_Net */

#ifndef _Included_com_questdb_network_Net
#define _Included_com_questdb_network_Net
#ifdef __cplusplus
extern "C" {
#endif
#undef com_questdb_network_Net_ERETRY
#define com_questdb_network_Net_ERETRY 0L
#undef com_questdb_network_Net_EPEERDISCONNECT
#define com_questdb_network_Net_EPEERDISCONNECT -1L
#undef com_questdb_network_Net_EOTHERDISCONNECT
#define com_questdb_network_Net_EOTHERDISCONNECT -2L
#undef com_questdb_network_Net_ECONNTIMEOUT
#define com_questdb_network_Net_ECONNTIMEOUT -3L

/*
 * Class:     io_questdb_client_network_Net
 * Method:    configureNonBlocking
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_configureNonBlocking
        (JNIEnv *, jclass, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    connect
 * Signature: (IJ)J
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_connect
        (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    freeMsgHeaders
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_questdb_client_network_Net_freeMsgHeaders
        (JNIEnv *, jclass, jlong);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    freeSockAddr0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_questdb_client_network_Net_freeSockAddr0
        (JNIEnv *, jclass, jlong);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    join
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_client_network_Net_join
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    msgHeaders
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_client_network_Net_msgHeaders
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    recv
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_recv
        (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    send
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_send
        (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    getSndBuf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_getSndBuf
        (JNIEnv *, jclass, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    setSndBuf
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_setSndBuf
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    setTcpNoDelay
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_setTcpNoDelay
        (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    sockaddr0
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_client_network_Net_sockaddr0
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    socketTcp
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_socketTcp
        (JNIEnv *, jclass, jboolean);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    getMsgHeaderSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_client_network_Net_getMsgHeaderSize
        (JNIEnv *, jclass);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    getMsgHeaderBufferAddressOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_client_network_Net_getMsgHeaderBufferAddressOffset
        (JNIEnv *, jclass);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    getMsgHeaderBufferLengthOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_client_network_Net_getMsgHeaderBufferLengthOffset
        (JNIEnv *, jclass);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    getEwouldblock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_getEwouldblock
        (JNIEnv *, jclass);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    socketUdp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_socketUdp
        (JNIEnv *, jclass);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    setMulticastInterface
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_setMulticastInterface
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    setMulticastTtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_setMulticastTtl
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    sendTo
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_sendTo
        (JNIEnv *, jclass, jint, jlong, jint, jlong);

/*
 * Class:     io_questdb_client_network_Net
 * Method:    sendToScatter
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_client_network_Net_sendToScatter
        (JNIEnv *, jclass, jint, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
